//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EarthTerminal.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EarthTerminal.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;.
        /// </summary>
        internal static string Program_Main__ {
            get {
                return ResourceManager.GetString("Program_Main__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;IsException&quot;:false,&quot;Token&quot;:&quot;16:24:30256&quot;,&quot;Type&quot;:&quot;Result&quot;,&quot;Value&quot;:[&quot;ground&quot;,&quot;round_btn&quot;,&quot;rect_btn&quot;,&quot;level[0]&quot;,&quot;handle&quot;,&quot;pointer&quot;,&quot;level[1]&quot;,&quot;level[2]&quot;,&quot;mouse&quot;]}.
        /// </summary>
        internal static string ResultMetadataSample {
            get {
                return ResourceManager.GetString("ResultMetadataSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;IsException&quot;:false,&quot;Token&quot;:&quot;16:24:30256&quot;,&quot;Type&quot;:&quot;Result&quot;,&quot;Value&quot;:&quot;aa&quot;}.
        /// </summary>
        internal static string ResultMetadataSample2 {
            get {
                return ResourceManager.GetString("ResultMetadataSample2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;SocketIdx&quot;: 1,
        ///	&quot;IsException&quot;: false,
        ///	&quot;Token&quot;: &quot;15:55:43861&quot;,
        ///	&quot;Type&quot;: &quot;Result&quot;,
        ///	&quot;Value&quot;: {
        ///		&quot;Value&quot;: {
        ///			&quot;Groups&quot;: [{
        ///				&quot;Guids&quot;: [&quot;A5A28C44-AD0E-4E09-BCB6-9B3F5061D03E&quot;, &quot;F79C157F-2FE5-4669-8AD9-5196204942F7&quot;, &quot;78685D25-B79E-4492-9369-8540CBA078C2&quot;, &quot;743FB45B-D189-4BA8-A6C9-A11B2130444C&quot;, &quot;84BB5378-8BF8-4D1A-AE89-6C6E75608AF6&quot;, &quot;E4985031-C950-4526-821F-AE2921017573&quot;, &quot;72E7B672-7715-43C3-A55C-7FAF4CC498B0&quot;, &quot;0D440435-97C7-4291-9582-2740286BBDA6&quot;, &quot;036CD5D7-D547-47CF-83D7-D8C4D0E06A0F&quot;, &quot;17 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string VrpResult1 {
            get {
                return ResourceManager.GetString("VrpResult1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;IsException&quot;: false,
        ///	&quot;Token&quot;: &quot;123&quot;,
        ///	&quot;Type&quot;: &quot;Result&quot;,
        ///	&quot;Value&quot;: {
        ///		&quot;Groups&quot;: [{
        ///			&quot;Name&quot;: &quot;vrp_rigid_danxiang&quot;
        ///		}, {
        ///			&quot;Name&quot;: &quot;vrp_rigid_duigaoji&quot;
        ///		}],
        ///		&quot;Models&quot;: [{
        ///			&quot;Name&quot;: &quot;xh_sky_吊车01&quot;,
        ///			&quot;Guid&quot;: &quot;84BB5378-8BF8-4D1A-AE89-6C6E75608AF6&quot;
        ///		}, {
        ///			&quot;Name&quot;: &quot;xh_sky_吊车02&quot;,
        ///			&quot;Guid&quot;: &quot;78685D25-B79E-4492-9369-8540CBA078C2&quot;
        ///		}]
        ///	}
        ///}.
        /// </summary>
        internal static string VrpResult2 {
            get {
                return ResourceManager.GetString("VrpResult2", resourceCulture);
            }
        }
    }
}
